apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackernews-api
  labels: 
    app: hackernews-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackernews-api
  template:
    metadata:
      labels:
        app: hackernews-api
    spec:
      containers:
      - name: hackernews-api
        image: hackernews/api:80
        ports:
          - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
          limits: 
            cpu: 300m
            memory: 500Mi

---

apiVersion: v1
kind: Service
metadata:
  name: hackernews-api-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: hackernews-api

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hackernews-api-ingress
  labels:
    app: hackernews-api-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hackernews-api-service
            port:
              number: 80